### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Mittelblut9** [emink06/card-flip#1]
Hey 👋 

i can give you some improvements in the file structure to make every project more organized and readable.

I work a lot with Folders. 
For this Project it could be like this for example 

```
<root>
 ---> <assets>
       ---->
            <images>
             your-images.png 
            <js>
             index.js
            <css>
             style.css
index.html

```

And naming of files is also important. In this case, you could name your images to that what they are displaying.
Example: `red_moon_city.png`

**Comment by emink06** [comment]
I didn't do this to just make it perfect, It's basically just a thing for learning and one friend asked me for code so i sent this tho him so... That's not an issue hahah. 😊
